config/routes.rb
Rails.application.routes.draw do
  root 'users#new'

  get 'dashbord', to: 'users#index' , as: 'dashbord'

  # get 'dashbord', to: 'users#index', as: 'dashbord'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'users#login', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'notifications/new'
  post 'notifications/create' => 'notifications#create', as: "sendsms"


  resources :users
  resources :sessions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true



  def clean_number
    number = self.number.scan(/\d+/).join
    number[0] == "1" ? number[0] = '' : number
    number unless number.length != 20
  end


end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :password, presence: true, :on => :create
  validates_uniqueness_of :phone_number
  validates_uniqueness_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  protected

    def authorize
      redirect_to '/login' unless current_user
    end

end

app/controllers/notifications_controller.rb
# app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def create
    MessageSender.send_messages
    redirect_to dashbord_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

def index
  redirect_to dashbord_path
end

  def create
    user = User.find_by(phone_number: params[:phone_number])
    if user #&& user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to dashbord_path, notice: "Logged in"
    else
      flash.now.alert ="Phone number is invalid"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # http_basic_authenticate_with :user, :email, :phone_number, :password
  # before_action :authorize
  def index
    @user = current_user || User.new(username: 'anonymous')
  end

  def new
    @user= User.new
  end


  def create
    @user = User.new(allowed_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to dashbord_path, notice: "Thank you for signing up. You will receive our notifications, via text message."
    else
      render "new"
    end
  end


  def show
  end

  def send_text
    @user = User.new(params[:phone_number])
    @user.send_sms(@user.clean_number)
    redirect_to :back
  end



  private
 def allowed_params
   params.require(:user).permit(:username, :email, :phone_number, :password, :password_digest)
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Parkvise</title>
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
  <body>
    <div id="user_header">
        <nav class="navbar navbar-inverse navy">
          <% if current_user %>
          <%= link_to 'Logout', logout_path, class:"glyphicon glyphicon-log-out logout1" %>
          <%= link_to 'Dashboard', sessions_path, class:"glyphicon glyphicon-user logout1" %>
            <%= link_to 'Register', new_user_path, class: "	glyphicon glyphicon-plus logout1"%>
          <% else %>
          <div class="head-buttons">

            <%= link_to 'Register', signup_path, class:"register1" %>
            <%= link_to "Log In", login_path, class:"register1" %>

          </nav>

      </div>
        </div>
    <% end %>
  </div>
  <%= yield %>
</body>
</html>

app/views/notifications/create.html.erb
<div class="send_alert">
  <%= button_to 'Send Alert', sendsms_path %>

</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="dashboard">

  <img src="http://andhrauniversity.edu.in/webnew/images/nopic.png" alt="logo"height="42" width="42">

<h1><%= @user.username  %></h1>

<ul>
  <li>Phone Number: <%= @user.phone_number %></li>
  <li>Email: <%= @user.email %></li>
</ul>

</div>
<div class= "new_user1">

  <%= button_to 'Parkvise!', sendsms_path , class:"btn btn-default btn-circle btn-xl"%>
</div>

app/views/users/login.html.erb
<div class="login_page">
    <h1>Log In</h1>
    <%= form_tag sessions_path do %>
    <div class="field">
      <%= label_tag :phone_number %><br />
      <%= text_field_tag :phone_number %>
    </div>


      <%= submit_tag "Log In", class:"actions" %>
</div>
<% end %>

app/views/users/new.html.erb
<div class="register">


<body class="sing_in">
<div class="sign">
  <h1>Parkvise</h1>
  <h1>No more ticket</h1>

  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% @user.errors.full_messages.each do |message|%>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

<div class="field">
  <%= f.label :username %> <br>
  <%= f.text_field :username %>
</div>

<div class="field">
  <%= f.label :phone_number%> <br>
  <%= f.text_field :phone_number %>
</div>
<div class="field">
  <%= f.label :email %> <br>
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :password %> <br>
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation %> <br>
  <%= f.password_field :password_confirmation %>
</div>
<br>

  <%= f.submit "Sign Up", class:"actions" %>

<% end %>

</div>